### PR TITLE
AmyLiu_hw1

### PR DESCRIPTION
**Pull request by amyLiu999**

### CODE REVIEW

**Comment by sssiyun** [comment]
Nice answer of hw1 questions

**Comment by CharlesCCC** [comment]
please re-create PR in your main branch and close this one.

**Comment by amyLiu999** [comment]
Close this one: AmyLiu_hw1 #10, and have created a new one: Amy liu/hw1 #38.

**Comment by amyLiu999** [comment]
> please re-create PR in your main branch and close this one.

Close this one: AmyLiu_hw1 #10, and have created a new one: Amy liu/hw1 #38.

**Pull request closed without merging**
